#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord state=floating

$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/.config/bg.jpg
picom
urxvtd -q -f
mpd
